# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='text',
        ),
    ]
